version: "3.9"
services:
    web:
        build: .
        ports:
            - "5005:5005"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "m7Vkh&ZeYJ9nTD5@asdTRkds"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"